### ISSUE TITLE
Image width

### ISSUE THREAD

**Issue by AlselwiAisha** [AbdulSalamAbro/portfoliowebsite#7]
_Hi AbdulSalam_
you have good code

- In screen size (768px), your desktop style looks like the Image. Please fix the width of the images.

![25](https://github.com/AbdulSalamAbro/portfoliowebsite/assets/123330794/7cab35a6-ec1d-4def-91b6-0288effe8c1d)

- you can fix that for example 

@media  (min-width: 768px) {
.
.
.
.portfolio-details{
  width: 98%;
}
.portfolio-details img{
  width: 80%;
  height: 50%;
}}

**Comment by AbdulSalamAbro** [comment]
Thanks Aisha for highlighting this issue I will implement it to make my project more responsive
